version: '3'

services:
  server:
    image: instantbox/instantbox:latest
    container_name: instantbox_server
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/apps/insta.derunix.ru/manifest.json:/app/manifest.json
    environment:
      - SERVERURL=insta.derunix.ru
    networks:
      - instantbox_net

  frontend:
    image: instantbox/instantbox-frontend:latest
    container_name: instantbox_frontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.insta_frontend.rule=Host(`insta.derunix.ru`)
      - traefik.http.routers.insta_frontend.entrypoints=websecure
      - traefik.http.routers.insta_frontend.tls.certresolver=myresolver
      - traefik.http.services.insta_frontend.loadbalancer.server.port=80
    links:
      - server
    expose:
      - 80
    networks:
      - instantbox_net

  cron:
    image: instantbox/cron:latest
    restart: always
    container_name: instantbox_cron
    links:
      - frontend
    environment:
      - CRON_STRINGS=* * * * * wget -qO /dev/null http://frontend/api/v2/superinspire/prune
    networks:
      - instantbox_net

networks:
  instantbox_net:
